from __future__ import annotations

from cce.memory.ltm import LongTermMemory
from cce.memory.stm import ShortTermMemory
from cce.memory.wm import WorkingMemory
from cce.models.types import MemoryRecord, PromptPackage
from cce.pipeline.chunker import estimate_tokens
from cce.settings import Settings

# Generic query used when no specific query is provided (e.g. /recall with no query).
# Embeds a description of project state to surface structurally important LTM records.
_GENERIC_RECALL_QUERY = (
    "current project state architecture decisions constraints "
    "function names file structure recent changes"
)

_BRIEFING_HEADER = "[CONTEXT BRIEFING — generated by Context Compression Engine]"
_BRIEFING_FOOTER = "[END BRIEFING]"


class PromptAssembler:
    """Assembles an optimized prompt from all three memory tiers.

    Algorithm:
      1. Pull all STM records (always included verbatim, newest-first)
      2. Query WM top-K by similarity
      3. Query LTM top-K by similarity
      4. Merge WM+LTM, rank by importance_score DESC
      5. Greedily fill remaining budget after STM is reserved
      6. Format into a structured briefing prefix + original message
    """

    def __init__(self, settings: Settings):
        self._settings = settings

    async def assemble(
        self,
        stm: ShortTermMemory,
        wm: WorkingMemory,
        ltm: LongTermMemory,
        query_embedding: list[float],
        current_message: str,
        max_context_tokens: int | None = None,
        top_k: int = 20,
    ) -> PromptPackage:
        budget = max_context_tokens or self._settings.default_max_context_tokens
        budget = int(budget / self._settings.token_count_padding_factor)
        budget -= self._settings.assembly_response_reserved_tokens
        budget -= estimate_tokens(_BRIEFING_HEADER) + estimate_tokens(_BRIEFING_FOOTER)

        # --- STM: always included ---
        stm_records = await stm.all()
        stm_tokens = sum(estimate_tokens(r.content) for r in stm_records)
        remaining = budget - self._settings.assembly_stm_reserved_tokens

        # --- WM + LTM: ranked by importance score ---
        wm_records = await wm.query(query_embedding, top_k=top_k)
        ltm_records = await ltm.query(query_embedding, top_k=top_k)

        combined = sorted(
            wm_records + ltm_records,
            key=lambda r: r.importance_score,
            reverse=True,
        )

        selected_wm: list[MemoryRecord] = []
        selected_ltm: list[MemoryRecord] = []

        for record in combined:
            cost = estimate_tokens(record.content)
            if remaining - cost < 0:
                break
            remaining -= cost
            from cce.models.types import MemoryTier
            if record.tier == MemoryTier.WM:
                selected_wm.append(record)
            else:
                selected_ltm.append(record)

        original_tokens = estimate_tokens(current_message) + stm_tokens
        compressed_tokens = (
            sum(estimate_tokens(r.content) for r in selected_wm)
            + sum(estimate_tokens(r.content) for r in selected_ltm)
            + stm_tokens
            + estimate_tokens(current_message)
        )

        prompt = self._format_prompt(
            stm_records, selected_wm, selected_ltm, current_message
        )

        return PromptPackage(
            project_id=stm_records[0].project_id if stm_records else "unknown",
            optimized_prompt=prompt,
            original_token_estimate=original_tokens,
            compressed_token_estimate=compressed_tokens,
            compression_ratio=round(original_tokens / max(compressed_tokens, 1), 2),
            stm_hits=len(stm_records),
            wm_hits=len(selected_wm),
            ltm_hits=len(selected_ltm),
        )

    async def recall(
        self,
        stm: ShortTermMemory,
        wm: WorkingMemory,
        ltm: LongTermMemory,
        query_embedding: list[float],
        max_tokens: int = 2048,
        top_k: int = 20,
    ) -> str:
        """Build a standalone briefing document for context reset injection."""
        budget = int(max_tokens / self._settings.token_count_padding_factor)

        wm_records = await wm.query(query_embedding, top_k=top_k)
        ltm_records = await ltm.query(query_embedding, top_k=top_k)

        combined = sorted(
            wm_records + ltm_records,
            key=lambda r: r.importance_score,
            reverse=True,
        )

        selected: list[MemoryRecord] = []
        remaining = budget
        for record in combined:
            cost = estimate_tokens(record.content)
            if remaining - cost < 0:
                break
            remaining -= cost
            selected.append(record)

        from cce.models.types import MemoryTier
        wm_sel = [r for r in selected if r.tier == MemoryTier.WM]
        ltm_sel = [r for r in selected if r.tier == MemoryTier.LTM]

        return self._format_briefing([], wm_sel, ltm_sel)

    # ------------------------------------------------------------------

    def _format_prompt(
        self,
        stm: list[MemoryRecord],
        wm: list[MemoryRecord],
        ltm: list[MemoryRecord],
        current_message: str,
    ) -> str:
        parts = [_BRIEFING_HEADER]

        if stm:
            parts.append("\n## Recent Context")
            for r in stm:
                parts.append(r.content)

        if wm:
            parts.append("\n## Working Knowledge")
            for r in wm:
                parts.append(f"- {r.content}")

        if ltm:
            parts.append("\n## Long-Term Memory")
            for r in ltm:
                parts.append(f"- {r.content}")

        parts.append(_BRIEFING_FOOTER)
        parts.append(f"\n{current_message}")
        return "\n".join(parts)

    def _format_briefing(
        self,
        stm: list[MemoryRecord],
        wm: list[MemoryRecord],
        ltm: list[MemoryRecord],
    ) -> str:
        parts = [_BRIEFING_HEADER]

        if wm:
            parts.append("\n## Working Knowledge")
            for r in wm:
                parts.append(f"- {r.content}")

        if ltm:
            parts.append("\n## Long-Term Memory")
            for r in ltm:
                parts.append(f"- {r.content}")

        if not wm and not ltm:
            parts.append("\n[No memory records available for this project yet.]")

        parts.append(_BRIEFING_FOOTER)
        return "\n".join(parts)
